### ISSUE TITLE
ModuleNotFoundError: No module named 'algo.ppo_transformer.mem_eff_experience

### ISSUE THREAD

**Issue by shahanneda** [hgaurav2k/hop#3]
Hi, 

Thanks for the great work!
I'm trying to run your code, but in file `algo/ppo_transformer/ppo_transformer.py` line 19 the code tries to import `from algo.ppo_transformer.mem_eff_experience import MemoryEfficientExperienceBuffer`, however this file is not included. 

Please let me know where I can find this!

**Comment by hgaurav2k** [comment]
Hi, 

Thanks for notifying this. This was a more efficient implementation of the replay buffer which we later did not use. We fix it in the latest commit. 

Thanks!
