### ISSUE TITLE
missing definition of the function 'run_multi_env'

### ISSUE THREAD

**Issue by qianqianlo** [hgaurav2k/hop#6]
Hi authors,

Thanks for sharing your great work! 

I tried to run /scripts/pretrain.py and visualize the manipulation process (on your provided checkpoint), but found that the function 'run_multi_env' was not defined. https://github.com/hgaurav2k/hop/blob/b331527eea99870a02bac0fa09117c2587761013/scripts/pretrain.py#L85

Could you please check the usage of this function? Thanks!

**Comment by hgaurav2k** [comment]
Hi,

Thanks for your interest. The latest commit adds run_multi_env to the model
